services:
  wildfly27:
    image: quay.io/wildfly/wildfly:27.0.1.Final-jdk11
    container_name: wildfly27
    ports:
      - 8080:8080
      - 5005:5005
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    volumes:
      - ../../../vul/vul-webapp-jakarta/build/libs/vul-webapp-jakarta.war:/opt/jboss/wildfly/standalone/deployments/app.war