services:
  tomcat6063:
    image: tomcat:6.0.53-jre7
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    volumes:
      - ../../../vul-webapp/build/libs/vul-webapp.war:/usr/local/tomcat/webapps/app.war