services:
  tomcat99:
    image: tomcat:9-jre9
    ports:
      - "8081:8080"
#      - "5005:5005"
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    volumes:
      - ../../../vul-webapp/build/libs/vul-webapp.war:/usr/local/tomcat/webapps/app.war